batch_size: 1
workers: 0
nepoch: 100
model_name: drlnet
load_model: Trained_model/drlnet.pth
start_epoch: 0
num_points: 1022
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
cuda_available: True
step_interval_to_print: 500
epoch_interval_to_save: 20
epoch_interval_to_val: 10
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30
testdata:  ./data/PPI/human/test


lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

layers: 1, 1, 1, 1
distribution_loss: KLD
knn_list: "16"
pk: 10
local_folding: True
points_label: True
num_coarse_raw: 256
num_fps: 2048
num_coarse: 1022

# test
save_vis: True
